# -*- coding: utf-8 -*-
"""basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xtVzMdaQsZoMdeuk2bg2t4pZlNgZMj0c
"""

from tensorflow.keras.layers import Dense,Input
from tensorflow.keras.models import Model

inputs = Input((1,))
outputs = Dense(1)(inputs)
model1 = Model(inputs,outputs)
model1.summary()

inputs = Input((2,))
x = Dense(4)(inputs)
outputs = Dense(2)(x)
model1 = Model(inputs,outputs)
model1.summary()

"""### Simple CNN"""

from tensorflow.keras.layers import Dense,Input,Conv2D,Flatten
from tensorflow.keras.models import Model

inputs = Input((28,28,1))
x = Conv2D(filters = 16,kernel_size = (3,3))(inputs)
x  = Flatten()(x)
outputs = Dense(1)(x)
model2 = Model(inputs,outputs)
model2.summary()

from tensorflow.keras.applications.vgg16 import VGG16
model3 = VGG16()
model3.summary()

model3.fit()
model3.evaluate()
model3.predict()