# -*- coding: utf-8 -*-
"""vgg16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vrM6IfY2htLUHlYrY3MRV6Og99U-fbXd
"""

import tensorflow as tf
from tensorflow.keras.layers import Dense,Conv2D,MaxPooling2D,Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import matplotlib.pyplot as plt

(x_train,y_train),(x_test,y_test)=tf.keras.datasets.mnist.load_data()

plt.figure(figsize=(7,7))
for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(x_train[i],cmap="gray")
    plt.title(y_train[i])
    plt.axis('off')
plt.show()

x_train=np.pad(x_train,((0,0),(10,10),(10,10)))
x_test=np.pad(x_test,((0,0),(10,10),(10,10)))

x_train=x_train.astype("float32")/255
x_test=x_test.astype("float32")/255

y_train=to_categorical(y_train,10)
y_test=to_categorical(y_test,10)

x_train=np.stack((x_train,)*3,axis=-1)
x_test=np.stack((x_test,)*3,axis=-1)

aug=ImageDataGenerator(
    rotation_range=10,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.1,
    zoom_range=0.1
)

aug.fit(x_train)
train_generator=aug.flow(x_train,y_train,batch_size=32)

model=tf.keras.Sequential()
model.add(VGG16(include_top=False,pooling="avg",weights="imagenet",input_shape=(48,48,3)))
model.add(Dense(512,activation="relu"))
model.add(Dense(10,activation="softmax"))

model.layers[0].trainable=False

model.summary()

model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=['acc'])

model.fit(train_generator,batch_size=32,epochs=10)

history=model.evaluate(x_test,y_test,verbose=0)
acc=history[1]
print("%.2f" %acc,"")

